### PR TITLE
feat-unacrchive: Added a unarchive conversion step

### PR DESCRIPTION
**Pull request by vanisrikanithi**
Unarchive go-conversion:
Added "Unarchive" support to go-convert specific to jenkins migration.

Unarchive Jenkins Trace:
[Vani_Unarchive.json](https://github.com/user-attachments/files/17896508/Vani_Unarchive.json)

go run main.go jenkinsjson --downgrade ~/go/Vani_Unarchive.json

Unarchive harness pipeline step:
```
- step:
    identifier: unarchive4bf5e3
    name: Unarchive
    spec:
      image: plugins/archive
      settings:
        action: extract
        exclude: ''
        format: zip
        glob: '**/*'
        overwrite: 'true'
        source: archive.zip
        target: unarchived_files/zip/
```

Unarchive Harness Pipeline [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Unarchive_Pipeline/deployments/gmEez38qT1SQjBauDCS_6A/pipeline?storeType=INLINE)

### CODE REVIEW

**Comment by vanisrikanithi** [comment]
Hello @Ompragash,

Could you please review the Unarchive PR and provide your comments on this?

Thank you.

**Comment by vanisrikanithi** [comment]
Hello @Ompragash ,

Updated the conversion step from run to plugin using plugis/archive, please review and provide your comments on this.

[Click](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Unarchive_Pipeline/deployments/gmEez38qT1SQjBauDCS_6A/pipeline?storeType=INLINE) here for harness pipeline.

Thank you.

**Comment by Ompragash** [comment]
@vanisrikanithi from the provided pipeline link, I noticed that you tested it only for the zip type. In the spec, you mentioned that the Jenkins unarchive step supports multiple formats like zip, tar, gz, etc.

Can you first confirm all the types supported by the Jenkins unarchive step? Then, test them with plugins/archive in Harness. If any type isn’t supported, we can consider adding it as an enhancement.

**Comment by vanisrikanithi** [comment]
@Ompragash made few changes to the existed plugin Achive to support the tar and gz formats as well tested successfully in the Harness pipeline. Below are the pipelines for different formats.

[zip](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Unarchive_Pipeline/deployments/1dbS7qAjQ4mV70m53Tqezw/pipeline?storeType=INLINE), [gz](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Unarchive_gz_Pipeline/deployments/ip8pQLh6SimmOFIv5FbNig/pipeline?storeType=INLINE), [tar](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Unarchive_tar_Pipeline/pipeline-studio?storeType=INLINE&stageId=Test_Vani_Unarchive&sectionId=EXECUTION).

Could you please review them and confirm the changes?

Thank you.

**Review by Ompragash — APPROVED** [review]

**Pull request merged**
